USERNAME := gestiweb
IMAGE_NAME := apache-server
IMAGE_TAG := latest
IMAGENAME_LABEL_TAG := dev

SHARE_FOLDER := /var/www/

include ../../utils/makefiles/network-lamp.mk


include ../../utils/makefiles/template.mk
