USERNAME := gestiweb
IMAGE_NAME := php5-fastcgi
IMAGE_TAG := latest
IMAGENAME_LABEL_TAG := dev

VOLUMES_FROM := apache-server-dev

include ../../utils/makefiles/network-lamp.mk


include ../../utils/makefiles/template.mk

