USERNAME := gestiweb
IMAGE_NAME := mariadb10-server
IMAGE_TAG := latest
IMAGENAME_LABEL_TAG := dev

SHARE_FOLDER := /var/lib/mysql


include ../../utils/makefiles/network-lamp.mk

include ../../utils/makefiles/template.mk

