#!/bin/sh

unset SESSION_MANAGER
#unset DBUS_SESSION_BUS_ADDRESS

#export XKL_XMODMAP_DISABLE=1

[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey

/usr/bin/openbox &
sleep 1

echo "Starting Eneboo . . ."
if [ -n "$ENEBOO_CONNSTRING" ]
then
    $HOME/scripts/timeout.sh 60 /usr/bin/display-im6 $HOME/Desktop/splashclient.png &
    /usr/local/bin/eneboo -silentconn "$ENEBOO_CONNSTRING"
else
    /usr/local/bin/eneboo
fi

echo "Eneboo closed."

