#!/bin/bash
CONTAINER_NAME=$1
TEST_COMMAND=/bin/true

CONTAINER_ID=$(docker ps -f name="$CONTAINER_NAME" -a -q)

if [ "$CONTAINER_ID" = "" ]; then
    >&2 echo "Container $CONTAINER_NAME does not exist."
    exit 5;
else
    echo $CONTAINER_ID
    exit 0;
fi

